[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "optiflow"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = ["numpy", "scikit-learn", "tqdm"]
